name: Build

on:
  push:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm install -g @neutralinojs/neu
      - run: neu build
      - run: ls -la dist/
      - uses: actions/upload-artifact@v4
        with:
          name: linux
          path: dist/

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm install -g @neutralinojs/neu
      - run: neu build
      - run: dir dist
      - uses: actions/upload-artifact@v4
        with:
          name: windows
          path: dist/
